name: gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    name: deploy(push) to gh-pages branch
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup node.js environments
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    # Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        
    # Install dependencies
    - run: npm install
      
    # Generate static files
    - run: npm run build
    
    # Deploy to gh-pages branch
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: blog.solidays.cn
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@solidays.cn'
        commit_message: ${{ github.event.head_commit.message }}
